import Head from "next/head";
import { Formik, Field, Form } from "formik";
import { useRouter } from "next/router";
export default function Home() {
  const { query } = useRouter();
  console.log(query.cat);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Formik
        initialValues={{
          categories: query.cat || "jewelery",
        }}
        onSubmit={async (values) => {
          fetch(
            `https://fakestoreapi.com/products/category/${values.categories}`
          )
            .then((res) => res.json())
            .then((json) => console.log(json));
        }}
      >
        <Form>
          <Field label="categories" as="select" name="categories">
            <option value="all">get all</option>
            <option value="electronics">electronics</option>
            <option value="jewelery">jewelery</option>
            <option value="men's clothing">men's clothing</option>
            <option value="women's clothing">women's clothing</option>
          </Field>
          <button type="submit">Submit</button>
        </Form>
      </Formik>
    </div>
  );
}
